[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev --legacy-peer-deps"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx tsc",
  "npx prisma db push --accept-data-loss --skip-generate || echo 'DB push skipped'"
]

[start]
cmd = "node dist/server.js"
