[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --omit=dev --legacy-peer-deps"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx tsc"
]

[start]
cmd = "npx prisma db push --skip-generate --accept-data-loss || true && node dist/server.js"

[start]
cmd = "node dist/server.js"
