[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm ci --legacy-peer-deps --include=optional",
  "npm rebuild sharp --platform=linux --arch=x64"
]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx tsc"
]

[start]
cmd = "node start-railway.js"
